#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#application="biotFoam"

runApplication blockMesh
runApplication setSet < batch.setSet
runApplication setsToZones -noFlipMap
#runApplication decomposePar
#runApplication mpirun -np 8 $application -parallel > log &
runApplication biotFoam  &

echo "PID=$!" > case.pid

