#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions



runApplication blockMesh
runApplication setSet < batch.setSet
runApplication setsToZones -noFlipMap
runApplication setFields

runApplication biotFoam &



