#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#application="biotFoam"

runApplication blockMesh
runApplication setSet < batch.setSet
runApplication setsToZones -noFlipMap
runApplication pressureBuildupFoam  &

echo "PID=$!" > case.pid

