#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#application="biotFoam"

runApplication blockMesh
runApplication setFields
runApplication biotFoam  &

echo "PID=$!" > case.pid

